### ISSUE TITLE
Create RESTful job endpoints

### ISSUE THREAD

**Issue by wagnerdk** [UST-MICO/mico#110]
As a user, I want to manage jobs like GitHub import or deployment tasks via a specified RESTful HTTP API. This is only the `jobs` enpoints, not the whole implementation of the job architecture. Depends on <https://github.com/UST-MICO/mico/issues/95> and <https://github.com/UST-MICO/mico/issues/144>.

```
POST /services/import/{type}
{
    url: "..."
    // ...
}
HTTP/1.1 202 Accepted
Location: /jobs/12345

---

GET /jobs/12345
HTTP/1.1 200 Ok
{
    "type": "IMPORT",
    "status": "PENDING",
    ...
    // "_embedded": {
    //     // import request object
    // },
    "_links": {
        "self": { "href": "/jobs/12345" },
        "cancel": { "method": "DELETE", "href": "/jobs/12345" },
    },
}

// If job has been finished
HTTP/1.1 303 See Other
Location: /services/{shortName}/{version} // depends on "type"

or

// If job info is no longer available (for whatever reason)
HTTP/1.1 410 Gone (once job information is no longer available, when the server expires the resource)

---

GET /jobs
HTTP/1.1 200 Ok
[ ... ]
```

**Comment by davidkopp** [comment]
The endpoint `POST /applications/{shortName}/{version}/deploy` must also be changed. It should return `202 Accepted` and point to the created job resource.

What should be the response to `GET /jobs/12345` if the deployment job is completed?
Because there is no new resource created (like in the example with the import job), I would suggest to point to the finally updated application resource.
