### ISSUE TITLE
Application Deployment Information

### ISSUE THREAD

**Issue by spethso** [UST-MICO/mico#409]
As a backend developer, I want to know if an application is at the moment deployed, so that I can fulfill e.g. delete requirements.

**Comment by buehlefs** [comment]
Implementation in the pull requests only checks for each service of the application if it is deployed. This will break in the extended scenario #390 as a service can be used by multiple applications.

**Comment by davidkopp** [comment]
@buehlefs Thanks for that hint!

I think the only solution is to store the unique names of all Kubernetes resources (`Deployment`, `Service`) that are used by a MicoApplication in our own database.
@JakobBenz Could this information be placed in the `deploymentInformation`? Or should there be something else?

**Comment by JakobBenz** [comment]
The current (restructured) (not yet in the master due to Neo4j issues) design of the deployment information uses a relationship with properties between a `MicoApplication` and a `MicoService`.

Of course, the list of unique names of Kubernetes resources _could_ be stored in the `MicoServiceDeploymentInfo`, but this would implicate that the information about the unique names of the Kubernetes resources used by a `MicoApplication` is spread across (possibly) multiple relationship entities. Considering that, a separate (single) node related to a `MicoApplication` holding all Kubernetes service/deployment unique names would be the simpler and better solution. The new domain object (node entity) could be called `MicoApplicationDeploymentInfo`.

**Comment by davidkopp** [comment]
I would prefer to store the unique names and maybe some more details about the actual deployment in the `MicoServiceDeploymentInfo` (or as a separate `NodeEntity` associated with the `MicoServiceDeploymentInfo`). I think with this approach we are more flexibel and are able to use this information also for other scenarios like aggregating all deployed *MicoApplications* that are actually using a specific deployed *MicoService*. That would be harder if this information is stored at the application node in a list of *MicoServices*.
