### ISSUE TITLE
If a service interface is added, no output topic should be required

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#844]
With the current implementation it is not allowed to deploy a Kafka-enabled service, that has a normal service interface but no output topic (input topic is set).
I think it should be allowed to deploy a Kafka-enabled service with no output topic, if there is a normal interface (e.g. http) defined.

**Comment by buehlefs** [comment]
We should not restrict the deployment of user created Kafka-enabled services. Even without specific topics and interfaces a service may just subscribe to a topic regex and send to dynamic topics.
The restrictions only work for the kafka-faas-connector because we know that it only passively listenes to new messages/events and the user provided faas can only react to those messages/events. Any other service can however actively send messages.
